default: &default
  host: localhost
  user: test
  password: test
  adapter: postgres
  migration_files_path: ./db/migrations
  skip_dumping_schema_sql: true

development:
  <<: *default
  db: app_db

test:
  <<: *default
  db: application_database_name_test

production:
  <<: *default
  db: application_database_name_production